service:
  build: ./Service
  volumes:
   - "./Service:/app"
  environment:
   - VIRTUAL_HOST=cams.dev
   - SERVER_MAX_CLIENTS=30
   - SERVER_MAX_BANDWIDTH=600000
   - VIDEO_BIT_RATE=13333
  ports:
   - '80:8080'

encoder_driveway:
  build: ./Encoder
  volumes:
   - "./Encoder:/app"
  links:
   - service
  environment:
   - CAMERA_NAME=driveway
   - CAMERA_SOURCE=rtsp://guest:guest@10.0.0.219:554/onvif1
   - CAMERA_OPTIONS= -buffer_size 5120000
