haproxy:
  image: tutum/haproxy:latest
  environment:
    - 'STATS_AUTH=stats:CaptainMorgan'
    - TIMEOUT=connect 50000, client 500000, server 500000
  links:
    - web
    - service
  ports:
    - '127.0.4.1:80:80'
    - '127.0.4.1:1936:1936'
  restart: always

web:
  build: ./Web
  links:
    - service
  volumes:
   - "./Web:/app"
  environment:
   - VIRTUAL_HOST=cams.dev
   - SERVER_MAX_CLIENTS=30
   - SERVER_MAX_BANDWIDTH=600000
   - VIDEO_BIT_RATE=13333

service:
  build: ./Service
  volumes:
   - "./Service:/app"
  environment:
   - VIRTUAL_HOST=stream.cams.dev
   - EXCLUDE_PORTS=80
   - SERVER_MAX_CLIENTS=30
   - SERVER_MAX_BANDWIDTH=600000
   - VIDEO_BIT_RATE=13333
  ports:
   - '127.0.4.1:8080:8080'

encoder_driveway:
  build: ./Encoder
  volumes:
   - "./Encoder:/app"
  links:
   - service
  environment:
   - CAMERA_NAME=driveway
   - CAMERA_SOURCE=rtsp://guest:guest@10.0.200.1:554/onvif1
   - CAMERA_SOAP=http://10.0.200.1:5000
   - CAMERA_OPTIONS= -buffer_size 5120000
   - CAMERA_ENABLE_PTZ=yes

encoder_back:
  build: ./Encoder
  volumes:
   - "./Encoder:/app"
  links:
   - service
  environment:
   - CAMERA_NAME=back
   - CAMERA_SOURCE=rtsp://guest:guest@10.0.200.3:554/onvif1
   - CAMERA_SOAP=http://10.0.200.3:5000
   - CAMERA_OPTIONS=-rtsp_transport udp
   - CAMERA_AUDIO_DISABLED=disabled
   - CAMERA_ENABLE_PTZ=yes

encoder_cartesian:
  build: ./Encoder
  volumes:
   - "./Encoder:/app"
  links:
   - service
  environment:
   - CAMERA_NAME=cartesian
   - CAMERA_SOURCE=http://a3e11fed.ngrok.io/main.webm
   - CAMERA_ENABLE_PTZ=no