service:
  image: camera/server
  environment:
   - VIRTUAL_HOST=cams.dev
   - EXCLUDE_PORTS=80
   - SERVER_MAX_CLIENTS=30
   - SERVER_MAX_BANDWIDTH=600000
   - VIDEO_BIT_RATE=13333
  ports:
   - '127.0.4.1:80:8080'

encoder_front:
  image: camera/encoder
  links:
   - service
  environment:
   - CAMERA_NAME=front
   - CAMERA_SOURCE=rtsp://guest:guest@10.0.200.2:554/onvif1
   - CAMERA_OPTIONS=-rtsp_transport udp

encoder_back:
  image: camera/encoder
  links:
   - service
  environment:
   - CAMERA_NAME=back
   - CAMERA_SOURCE=rtsp://guest:guest@10.0.200.3:554/onvif1
   - CAMERA_OPTIONS=-rtsp_transport udp
   - CAMERA_AUDIO_DISABLED=disabled

encoder_driveway:
  image: camera/encoder
  links:
   - service
  environment:
   - CAMERA_NAME=driveway
   - CAMERA_SOURCE=rtsp://guest:guest@10.0.200.1:554/onvif1
   - CAMERA_OPTIONS=-rtsp_transport udp

encoder_mattCam:
  image: camera/encoder
  links:
   - service
  environment:
   - CAMERA_NAME=mattCam
   - CAMERA_SOURCE=rtsp://guest:guest@10.0.200.4:554/onvif1
   - CAMERA_OPTIONS=-rtsp_transport udp

encoder_cartesian:
  image: camera/encoder
  links:
   - service
  environment:
   - CAMERA_NAME=cartesian
   - CAMERA_SOURCE=http://a3e11fed.ngrok.io/main.webm

recorder:
  image: camera/recorder
  volumes:
   - "/media/CCTV:/video"
  links:
   - service
